version: "3"

services:
  phone-list-be:
    build: ./phone-list-be
    ports:
      - 5001:5001
    volumes:
      - ./phone-list-be:/app
    env_file:
      - .env

  phone-list-fe:
    build: ./phone-list-fe
    ports:
      - 5002:4000
    volumes:
      - ./phone-list-fe:/app
    working_dir: /app
    command: yarn dev
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
